### ISSUE TITLE
Unable to resolve module `buffer`

### ISSUE THREAD

**Issue by Jancat** [feross/safe-buffer#18]
My node version is `v9.2.1`

Does the node doesn't support the deprecated grammer ?
```js
var buffer = require('buffer')
```

**Comment by feross** [comment]
@Jancat Sorry, I don't understand your question. This module is called `safe-buffer` not `buffer`.

**Comment by Jancat** [comment]
The [safe-buff/index.js](https://github.com/feross/safe-buffer/blob/master/index.js) **line 2**

It throws the error:

Unable to resolve module `buffer `from ./node-modules/safe-buff/index.js: Module does not exist in the module map

**Comment by lfernando-silva** [comment]
Iam having the same error, actually the module buffer is not listed at package.json

**Comment by Jancat** [comment]
@lfernando-silva Yes, I'm woking on react-native too. Do you have a good idea to fix the issue or an alternative  solution to use `sha package` in react-native?

**Comment by lfernando-silva** [comment]
I think installing buffer by npm install --save [buffer](https://www.npmjs.com/package/buffer) and using [rn-nodeify](https://www.npmjs.com/package/rn-nodeify) to makes adapt Buffer native module, it may to work, but not sure. Maybe you will adapt some other modules of sha package. 

In my case, I just replaced bip39 lib to react-native-bip39 and this part is ok now, because does not uses safe-buffer.

**Comment by Jancat** [comment]
Ok, thanks! I will have a try. @lfernando-silva

**Comment by feross** [comment]
You might find this issue useful if you're using react-native: https://github.com/facebook/react-native/issues/14796
